# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/_tflow_select-2.3.0-mkl.conda
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2020.6.20-hecda079_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ld_impl_linux-64-2.34-hc38a660_9.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgfortran-ng-7.5.0-hdf63c60_15.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-9.3.0-hdf63c60_15.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/mpi-1.0-openmpi.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgomp-9.3.0-h24d8f2e_15.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-1_gnu.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-9.3.0-h24d8f2e_15.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-h516909a_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/c-ares-1.16.1-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/expat-2.2.9-he1b5a44_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gmp-6.2.0-he1b5a44_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/graphite2-1.3.13-he1b5a44_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/icu-64.2-he1b5a44_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jpeg-9d-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/lame-3.100-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libffi-3.2.1-he1b5a44_1007.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libiconv-1.15-h516909a_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libopenblas-0.3.10-pthreads_hb3c22a3_4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libuuid-2.32.1-h14c3975_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libwebp-base-1.1.0-h516909a_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxkbcommon-0.10.0-he1b5a44_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/lz4-c-1.9.2-he1b5a44_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ncurses-6.2-he1b5a44_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/nettle-3.4.1-h1bed415_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/nspr-4.27-he1b5a44_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.1.1g-h516909a_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pcre-8.44-he1b5a44_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pixman-0.38.0-h516909a_1003.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pthread-stubs-0.4-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/x264-1!152.20180806-h14c3975_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-kbproto-1.0.7-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libice-1.0.10-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxau-1.0.9-h14c3975_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxdmcp-1.1.3-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-renderproto-0.11.1-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-xextproto-7.3.0-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-xproto-7.0.31-h14c3975_1007.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.5-h516909a_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zlib-1.2.11-h516909a_1007.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gettext-0.19.8.1-hc5be6a0_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gnutls-3.6.13-h79a8f9a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/hdf5-1.10.6-nompi_h3c11f04_101.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jasper-1.900.1-h07fcdf6_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libblas-3.8.0-17_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libllvm9-9.0.1-he513fc3_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libpng-1.6.37-hed695b0_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libprotobuf-3.12.4-h8b12597_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxcb-1.13-h14c3975_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxml2-2.9.10-hee79883_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openh264-2.1.1-h8b12597_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openmpi-4.0.4-hdf1f1ad_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/readline-8.0-he28a2e2_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.6.10-hed695b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libsm-1.2.3-h84519dc_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zstd-1.4.5-h6597ccf_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/freetype-2.10.2-he06d7ca_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libcblas-3.8.0-17_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libclang-9.0.1-default_hde54327_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/liblapack-3.8.0-17_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libtiff-4.1.0-hc7e4089_6.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sqlite-3.32.3-h4cf870e_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libx11-1.6.11-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ffmpeg-4.3.1-h167e202_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fontconfig-2.13.1-h86ecdb6_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/lcms2-2.11-hbd6801e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/liblapacke-3.8.0-17_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/nss-3.55-he751ad9_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-3.8.5-h4d41432_2_cpython.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxext-1.3.4-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxrender-0.9.10-h516909a_1002.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/astor-0.8.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/blinker-1.4-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cachetools-4.1.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/click-7.1.2-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/gast-0.3.3-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/glib-2.65.0-h6f030ca_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/idna-2.10-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/olefile-0.46-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-0.4.8-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pycparser-2.20-pyh9f0ad1d_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyparsing-2.4.7-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.8-1_cp38.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pytz-2020.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/six-1.15.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tensorboard-plugin-wit-1.6.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/termcolor-1.1.0-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/werkzeug-1.0.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wheel-0.35.1-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/zipp-3.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/absl-py-0.9.0-py38h32f6830_1.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/astunparse-1.6.3-py_0.conda
https://conda.anaconda.org/conda-forge/linux-64/cairo-1.16.0-hcf35c78_1003.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/certifi-2020.6.20-py38h32f6830_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cffi-1.14.1-py38h5bae8af_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/chardet-3.0.4-py38h32f6830_1006.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cycler-0.10.0-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/dbus-1.13.6-he372182_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/google-pasta-0.2.0-pyh8c360ce_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gstreamer-1.14.5-h36ae1b5_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/importlib-metadata-1.7.0-py38h32f6830_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/kiwisolver-1.2.0-py38hbf85e49_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/mpi4py-3.0.3-py38h246a051_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/numpy-1.19.1-py38h8854b6b_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pillow-7.2.0-py38h9776b28_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyasn1-modules-0.2.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pysocks-1.7.1-py38h32f6830_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/python-dateutil-2.8.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/rsa-4.6-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tornado-6.0.4-py38h1e0a361_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/typing-3.7.4.3-py38h32f6830_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/wrapt-1.12.1-py38h1e0a361_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/brotlipy-0.7.0-py38h1e0a361_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cryptography-3.0-py38h766eaa4_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gst-plugins-base-1.14.5-h0935bb2_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/h5py-2.10.0-nompi_py38hfb01d0b_104.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/harfbuzz-2.4.0-h9f30f68_3.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/markdown-3.2.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/opt_einsum-3.3.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pandas-1.1.0-py38h950e882_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/scipy-1.5.2-py38h8c5af15_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/setuptools-49.6.0-py38h32f6830_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/google-auth-1.20.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/grpcio-1.31.0-py38h2c89da0_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/keras-preprocessing-1.1.0-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/matplotlib-base-3.3.1-py38h91b0d89_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pip-20.2.2-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/protobuf-3.12.4-py38h950e882_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyjwt-1.7.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyopenssl-19.1.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/qt-5.12.5-hd8c4c69_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libopencv-4.4.0-py38_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/matplotlib-3.3.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/oauthlib-3.0.1-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tensorflow-base-2.2.0-mkl_py38h5059a2d_0.conda
https://conda.anaconda.org/conda-forge/noarch/tensorflow-estimator-2.2.0-pyh95af2a2_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/urllib3-1.25.10-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/py-opencv-4.4.0-py38h23f93f0_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/requests-2.24.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/opencv-4.4.0-py38_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/requests-oauthlib-1.3.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/google-auth-oauthlib-0.4.1-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tensorboard-2.3.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/tensorflow-2.2.0-mkl_py38h6d3daf0_0.conda
