# ezCGP pbs script
#PBS -N nvidia-smi
#PBS -l nodes=2:ppn=8:gpus=2:exclusive_process
#PBS -l pmem=1gb
#PBS -l walltime=8:00:00
#PBS -q pace-ice-gpu
#PBS -j oe
#PBS -o nvidia-smi.out
#PBS -m abe
#PBS -M szhang460@gatech.edu

cd ~/ezCGP
echo "Started on `/bin/hostname`"               # prints the name of the node job started on
module load java/1.8.0_25
module load openmpi/2.1.1
module load glib/2.40.0 
module load gcc/4.8.0
module load anaconda3
source activate ezCGP
nvidia-smi
